apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements: 
      - cluster: engineering-dev
        url: https://34.68.28.6 # faux cluster URLs
      - cluster: engineering-prod
        url: https://kubernetes.default.svc

  template: 
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/Shivaraj600/argo-demo.git
        targetRevision: HEAD
        # 'cluster' name is also substituted here
        path: deploy/
      destination:
        # The cluster 'url', used by Argo CD to access the cluster, is 
        # substituted here.
        server: '{{url}}'
        namespace: guestbook